//
// Created by 16905 on 25-7-20.
//

#ifndef COLORS_H
#define COLORS_H

#include "bricks.h"
/**
 *颜色系统宏定义规则：
 *不同砖块的颜色对序号=该砖块类型宏定义值x10+砖块此时的生命值
 *
 *不同砖块消除信息颜色对序号=该砖块宏定义值x10
 *
 *小球颜色对序号=所属对象宏定义值x100，挡板=小球+1
 */
#define NORMAL_BRICK_COMPLETE_COLOR NORMAL_BRICK*10+3
#define NORMAL_BRICK_HURT_COLOR NORMAL_BRICK*10+2
#define NORMAL_BRICK_BROKEN_COLOR NORMAL_BRICK*10+1
#define PRECIOUS_BRICK_COMPLETE_COLOR PRECIOUS_BRICK*10+2
#define PRECIOUS_BRICK_BROKEN_COLOR PRECIOUS_BRICK*10+1
#define HURT_BRICK_COMPLETE_COLOR HURT_BRICK*10+2
#define HURT_BRICK_BROKEN_COLOR HURT_BRICK*10+1
#define SPEED_BRICK_COMPLETE_COLOR SPEED_BRICK*10+2
#define SPEED_BRICK_BROKEN_COLOR SPEED_BRICK*10+1
#define HELP_BRICK_COMPLETE_COLOR HELP_BRICK*10+2
#define HELP_BRICK_BROKEN_COLOR HELP_BRICK*10+1

#define BALL1_COLOR 100
#define PADDLE1_COLOR 101
#define BALL2_COLOR 200
#define PADDLE2_COLOR 201
#define BOOM_MESSAGE_COLOR NORMAL_BRICK*10
#define YEAH_MESSAGE_COLOR PRECIOUS_BRICK*10
#define OOPS_MESSAGE_COLOR HURT_BRICK*10
#define HELP_MESSAGE_COLOR HELP_BRICK*10
#define DASH_MESSAGE_COLOR SPEED_BRICK*10

void init_colors();

#endif //COLORS_H
